### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by ValarDragon** [Pyhscript/CTFNoteTaker#5]
Suggestion: 
When other people login, have bot tell them how many new notes there are since they left, so we would have to log time since they last logged in, and timestamp of each note. Also there should be a configuration parameter to disable it per person (blacklist), or alternatively a whitelist.

**Comment by bnadarevic** [comment]
good idea, since not everyone in channel I think we should do it so every person decides for themselves if they want to get notification or not

**Comment by bnadarevic** [comment]
feature has been added
